// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CodeEditorController from "./code_editor_controller"
application.register("code-editor", CodeEditorController)

import CodeShareController from "./code_share_controller"
application.register("code-share", CodeShareController)

import LiveSearchController from "./live_search_controller"
application.register("live-search", LiveSearchController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)
