[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = ["bundle install", "yarn install --frozen-lockfile"]

[phases.build]
cmds = ["bundle exec rake assets:precompile", "bundle exec rake assets:clean"]

[start]
cmd = "bundle exec puma -C config/puma.rb"