[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
  "bundle install",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build:css",
  "bundle exec rails assets:precompile"
]

[start]
cmd = "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT"