[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
RAILS_ENV = "production"
BUNDLE_WITHOUT = "development:test"
RAILS_LOG_TO_STDOUT = "enabled"
RAILS_SERVE_STATIC_FILES = "true"